version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.12
    commands:
     - echo "installing dependencies"
     - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "zipping dep package"
      - zip -r deployment_package.zip lib 
      - ls -l
      - zip -g deployment_package.zip lambda_function.py
  post_build: 
    commands:
      - echo "updating lambda function"
      - aws lambda update-function-code --function-name Yalla_Ps_backend --zip-file fileb://deployment_pack
      - echo "Done" 
